export default {
          LOGIN: 'लॉग इन करें',
          LOGOUT: 'लॉग आउट',
          SIGNUP: 'साइन अप करें',
          EMAIL: 'ईमेल',
          PASSWORD: 'पासवर्ड',
          FORGETPASSWORD: 'पासवर्ड भूल गए',
          PHONENUMBER: 'फ़ोन नंबर',
          DOB: 'जन्म की तारीख',
          MALE: 'पुरुष',
          FEMALE: 'महिला',
          OTHER: 'अन्य',
          CONFIRM_PASSWORD: 'पासवर्ड की पुष्टि कीजिये',
          GENDER: 'लिंग',
          CITY: 'शहर',
          FIRSTNAME: 'पहला नाम',
          LASTNAME: 'उपनाम',
          LOCATION: 'स्थान',
          ADDRESS: 'पता',
          PINCODE: 'पिनकोड / ज़िपकोड',
          GETSTARTED: 'शुरू हो जाओ',
          NEXT: 'अगला',
          SUBMIT: 'प्रस्तुत',
          DONE: 'किया हुआ',
          TERMS: 'नियम एवं शर्तें',
          ENGLISH: 'अंग्रेज़ी',
          HINDI: 'हिन्दी',
          PLOGIN: 'मोबाइल के साथ लॉगिन करें',
          ENTER_YOUR_PHONE_NUMBER: 'अपना फोन नंबर दर्ज करें',
          ENTER_REQ_DIGIT_OTP: 'आपको भेजा गया 4-अंकीय कोड दर्ज करें',
          RESEND_OTP: 'ओटीपी पुनः भेजें',
          DID_NT_RECEVI_OTP: "क्या ओटीपी प्राप्त नहीं हुआ?",
          REQUES_FOR_OTP: ' ओटीपी के लिए अनुरोध',
          OTP_IN: '',
          OK: 'ठीक है',
          SIGNUP_USING_SOCIAL: 'अपने सामाजिक खाते का उपयोग करके साइन अप करें',
          SIGNIN_USING_SOCIAL: 'अपने सामाजिक खाते का उपयोग करके साइन इन करें',
          BY_CLICK_SIGNUP: ` "साइन अप" पर क्लिक करके, आप हमारे लिए सहमत हैं`,
          OUR_TERM_CONDITIONS: ' नियम एवं शर्तें',
          AS_WELL_AS: 'साथ ही साथ',
          PRIVACY_POLICY: 'गोपनीयता नीति',
          TO_AGREE: '', //for TERM_&CONDITION REQURIED FOR HINDI,
          PLS_ENTER_EMAIL: 'कृपया ईमेल दर्ज करें',
          WELCOME_BACK: 'वापसी पर स्वागत है!',
          PLS_ENTER_VALID_PHONE: 'कृपया एक वैध नंबर डालें',
          CREATE_YOUR_ACCOUNT: 'अपने खाते बनाएँ!',
          ENTER_EMAIL_FOR_PWD_LINK:
            'अपना ईमेल दर्ज करें और हम आपको भेज देंगे। अपना पासवर्ड रीसेट करने के निर्देश।',
          PLS_ENTER_VALID_EMAIL: 'कृपया वैध ईमेल दर्ज़ करें',
          PLS_ENTER_VALID_OTP: 'कृपया मान्य ओटीपी दर्ज करें',
          PLS_UPLOAD_IMAGE: 'कृपया एक छवि अपलोड करें',
          PASSWORD_INCORRECT: 'पासवर्ड गलत है',
          PASSWORD_REQUIRES_SIX_DIGIT: 'पासवर्ड के लिए न्यूनतम 6 वर्णों की आवश्यकता होती है',
          PASSWORD_CONFIRM_PWD_DIDNT_MATCH:
            "पासवर्ड और पुष्टि पासवर्ड मेल नहीं खाते",
          THANKS_FOR_INTEREST_COUNTRY:
          "आपकी रुचि के लिए धन्यवाद। हमारे ऑपरेशन वर्तमान में केवल भारत में उपलब्ध हैं। निकट भविष्य में आपसे उलझने की आशा कर रहा है। ",
          YOU_ARE_READY_TO_GO: 'तुम जाने के लिए तैयार हो!',
          THAKS_FOR_ACCOUNT_CREATION:
            "हमारे साथ खाता बनाने के लिए आपके समय के लिए धन्यवाद। ऐप की खोज करने के लिए कृपया सरल प्रश्नों के उत्तर देकर हमें अपने बारे में अधिक बताएं",
          PLEASE_SELECT_YOUR_LANGUAGE: 'कृपया अपनी भाषा चुनें',
          CHECK_YOUR_EMAIL: 'अपने ईमेल की जाँच करें',
          WE_HAVE_SENT_INSTRUCATION:
            "हमने पासवर्ड रीसेट करने के निर्देश दिए हैं (स्पैम की जाँच भी करें)",
          CHOOSE_YOUR_LANGUAGE: 'अपनी पसंदीदा भाषा चुनें',
          OR: 'या',
          SURVEY_FOR_YOU: 'आपके लिए सर्वेक्षण',
          BROWSE_SURVEY: 'सर्वेक्षण ब्राउज़ करें',
          REFER_A_FRIEND: 'मित्र को आमंत्रित करें',
          WIN_REWARD: 'और पुरस्कार जीतें',
          EARNED_REWARD: 'कमाया हुआ इनाम',
          HOME: 'घर',
          WALLET: 'बटुआ',
          SURVEYS: 'सर्वेक्षण',
          OFFER: 'प्रस्ताव',
          MORE: 'अधिक',
          FAQ: 'सामान्य प्रश्न',
          CONTACT_US: 'संपर्क करें',
          CONTACT_THROUGHT_PHONE: 'फोन के माध्यम से संपर्क करें',
          CONTACT_THROUGHT_Email: 'ईमेल के माध्यम से संपर्क करें',
          TYPE_HERE: 'यहा लिखो...',
          NOTIFICATION: 'सूचनाएं',
          MY_WALLET: 'मेरा बटुआ',
          CASH: 'नकद',
          COUPONS: 'कूपन',
          POINTS: 'अंक',
          TOTAL_COINS: 'कुल सिक्के',
          REDEEM: 'के एवज',
          EXPIRES: 'समय-सीमा समाप्त',
          DISCOUNT: 'छूट',
          TOTAL_POINTS: 'कुल अंक',
          ALL_SURVEY: 'सभी सर्वेक्षण',
          HISTORY: 'इतिहास',
          LIVE: 'लाइव',
          INDUSTRY: 'उद्योग',
          DURATION: 'सर्वेक्षण अवधि',
          REWARDS: 'पुरस्कार',
          FILTER_SORTING: 'फ़िल्टर करें और छाँटें',
          SEARCH: 'खोज',
          CATEGORY: 'वर्ग',
          OPEN: 'खुला हुआ',
          CLOSED: 'बंद किया हुआ',
          COMPLETED: 'पुरा होना',
          APPLY_FILTER: 'फिल्टर लागू करें',
          CLEAR_FILER: 'स्पष्ट निस्यंदक',
          STATUS: 'स्थिति',
          USER_INFO: 'यूजर जानकारी',
          PHONE: 'फ़ोन',
          COMPLETE_PROFILE_REWARD: 'अपनी प्रोफ़ाइल पूरी करें और पुरस्कार अर्जित करें',
          COMPLETE_PROFILE: 'पूरा प्रोफ़ाइल',
          SAVE: 'बचा ले',
          NEW_SURVEY: 'नया सर्वेक्षण',
          SUCCESSFULLY_COMPLETED: 'सफलतापूर्वक पूर्ण हुआ',
          POINTS_GET: 'आपके सर्वेक्षण का उत्तर \ n दिया गया है और आपको मिल जाएगा',
          RESET_INSTRUCTIONS:
            'हमने \ n पासवर्ड रीसेट करने के लिए निर्देश भी भेजे हैं (स्पैम फ़ोल्डर की भी जाँच करें)।',
          RESET_PASSWORD: 'पासवर्ड रीसेट',
          ENTER_YOUR_NEW_PASSWORD:
            'अपना नया पासवर्ड डालें और अपने DdipstiQ खाते के लिए नए पासवर्ड की पुष्टि करें।',
          YES: 'हाँ',
          NO: 'नहीं ',
          LOGOUT: 'लॉग आउट',
          ARE_YOU_SURE_YOU_WANT_TO_LOGOUT: 'क्या आप लॉग आउट करना चाहते हैं',
          ARE_YOU_SURE_YOU_WANT_TO_DEACTIVATE:
            'क्या आप वाकई अपना खाता निष्क्रिय करना चाहते हैं?',
          DEACTIVATE: 'निष्क्रिय करें',
          NEW_PASSWORD: 'नया पासवर्ड',
          PLEASE_ENTER_PASSWORD: 'कृप्या पास्वर्ड भरो',
          PLEASE_ENTER_NEW_PASS: 'कृपया नया पासवर्ड दर्ज करें',
          QUESTIONS: 'प्रशन',
          UNSATISFIED: 'असंतुष्ट',
          SATISFIED: 'संतुष्ट',
          GREAT: 'वाह् भई वाह',
          GOOD: 'अच्छा',
          NEXT: 'अगला',
          BACK: 'वापस',
          COMPLETE: 'पूर्ण',
          OFFER: 'ऑफर',
          FAQ: 'सामान्य प्रश्न',
          ADD_REFERAL_CODE:"रेफरल कोड जोड़ें",
          PLEASE_SELECT_AN_OPTION:"कृपया एक विकल्प चुनें",
          ENTER_TEXT:"लिखना प्रारम्भ करें",
          GETTING_STARTED:"शुरू करना",
          LOGIN_TO_YOUR_ACCOUNT:"Log in to your account",
          PROFILE:"प्रोफ़ाइल"
        };